### PR TITLE
Some Updates for Engineering

### PR DESCRIPTION
**Pull request by L10R**
Mehmet wanted some contend to be updates on the website.

### CODE REVIEW

**Comment by DrAdamRoe** [comment]
@CSNWEB this PR is directly into master; if I accept it will be auto-deployed to the live site, right? we don't want that, we want it on dev so the other Lucas can approve and push it live (I think). Should Lukas do a PR to dev, or will that not autodeploy?

**Comment by chrisstaudt** [comment]
It will autodeploy, so yes the PR should be made on dev
Am 15.12.2016 um 14:44 schrieb Adam Roe <notifications@github.com<mailto:notifications@github.com>>:


@CSNWEB<https://github.com/CSNWEB> this PR is directly into master; if I accept it will be auto-deployed to the live site, right? we don't want that, we want it on dev so the other Lucas can approve and push it live (I think). Should Lukas do a PR to dev, or will that not autodeploy?

**Comment by DrAdamRoe** [comment]
@lukasreussner could you PR to dev instead of master plz?

**Comment by L10R** [comment]
@adamjroe Done

**Comment by L10R** [comment]
@adamjroe The changes aren't live jet. I think you still have to merge them into master.

**Pull request merged**
